### ISSUE TITLE
Remove all references to Comments model

### ISSUE THREAD

**Issue by MikeGShelby** [MikeGShelby/diet-delivery#3]
Remove all references to Comments model from the following sections:
- Models
- API routes
- Handlebars templates

REMINDERS: 
- checkout into the relevant feature branch (example: feature/api when editing api routes)
- Update each branch you're working in before making edits. Do this with 'git pull origin main' when inside that branch.

**Comment by RickySulli** [comment]
I did a search and only find any references to this in the package-lock file.
