### ISSUE TITLE
Create Front-End Javascript for Diet Filter Buttons

### ISSUE THREAD

**Issue by MikeGShelby** [MikeGShelby/diet-delivery#9]
THIS IS IN PROGRESS

- Add front-end Javascript to homepage
- Functionality will allow user to select multiple diet filter buttons to filter meals that are returned on homepage
- Add a submit button
- Each filter button will be part of a multi-select form

OTHER 
- NOTE: empty front-end JS file has already been added: _public/javascript/filter-meals.js_
- (Similar front-end Javascript can be found in the Zookeepr project)

**Comment by RickySulli** [comment]
I didn't add a submit button, but I do have each button appending an associated array from the menu.  This isn't how we ultimately want it, but it is a start.

**Comment by MikeGShelby** [comment]
That sounds like a good start, at least for the presentation!

**Comment by MikeGShelby** [comment]
The filter buttons work great. Awesome job, Ricky! I'll close this issue now.
